### ISSUE TITLE
why many times I see length as NULL?

### ISSUE THREAD

**Issue by RodenLuo** [RodenLuo/cpp_questions#8]
![image](https://user-images.githubusercontent.com/8460424/114272573-69863980-9a1f-11eb-9ab6-58d267918b1c.png)

**Comment by ondrejstrnad** [comment]
Beware that it's not length BUT pointer to length. That's why it can be NULL. If the parameter was GLsizei, it could not be NULL. When a parameter is set to NULL it many times means that "I don't care" of "default" OR it can be a return value from the function. In this case, this is really a return value. See: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGetProgramInfoLog.xhtml
